export const AUTH_USER_CHANGE_EMAIL = '[AUTH] USER_CHANGE_EMAIL';
export const AUTH_USER_CHANGE_PASSWORD = '[AUTH] USER_CHANGE_PASSWORD';
export const AUTH_USER_LOGIN = '[AUTH] USER_LOGIN';
export const AUTH_USER_LOGIN_SUCCESS = '[AUTH] USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGIN_FAIL = '[AUTH] USER_LOGIN_FAIL';
export const AUTH_USER_RESET_FIELD = '[AUTH] USER_RESET_FIELD';
export const AUTH_SET_USER = '[AUTH] SET_USER';
export const AUTH_USER_SIGN_OUT = '[AUTH] USER_SIGN_OUT';
